import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { checkStatus } from "@/action/checkStatus.action";
import ErrorConnectServer from "@/components/ErrorConnectServer";
import { ThemeProvider } from "@/app/themeContext";
import { getConfigByKey } from "@/action/config.action";
import { LayoutType } from "@/lib/type";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const serverStatus = await checkStatus();
  if (!serverStatus) {
    return (
      <ErrorConnectServer />
    )
  }

  const layout = await getConfigByKey('layout')
  const layoutParse = JSON.parse(layout?.config_value || '') as LayoutType
  const themeMode = layoutParse.themeMode

  return (
    <ThemeProvider>
      <html lang="en" className={`${themeMode === 1 ? 'dark' : ''}`}>
        <body
          className={`antialiased flex justify-center`}
        >
          {children}
          <Toaster position="top-right" richColors />
        </body>
      </html>
    </ThemeProvider>
  );
}
