server:
  mode: "debug"
  host: "0.0.0.0"
  port: 9000
  mainServer: "0.0.0.0:9090"

logger:
  level: "debug"
  filename: "./storages/gateway.log"
  maxSize: 500
  maxBackups: 3
  maxAge: 28
  compress: true