"use server";
import { getConfigByKey } from "@/actions/config.action";
import { getImageById } from "@/actions/image.action";
import { ConfigType, SiteIdentifyType } from "@/lib/types";

type MetadataType = {
  title?: string;
  description?: string;
  icons?: {
    rel: string;
    type?: string;
    url: string;
    sizes?: string;
  }[];
  openGraph?: {
    type: string;
    url: string;
    title: string;
    description?: string;
    images?: {
      url: string;
      alt: string;
      width: number;
      height: number;
    }[];
  };
  twitter?: {
    handle: string;
    site: string;
    cardType: string;
  };
  canonical?: string;
};

export const generateMetadata = async ({
  title,
  description,
  openGraph,
  twitter,
  icons,
}: MetadataType) => {
  const meta: ConfigType = await getConfigByKey("header_siteidentify");
  const metaParse: SiteIdentifyType = JSON.parse(meta.config_value);
  const siteName = metaParse.title;
  const siteDescription = metaParse.description;
  const siteFavicon = metaParse.favicon;
  const favicon = await getImageById(siteFavicon);
  return {
    metadataBase: new URL(process.env.NEXT_PUBLIC_BASE_URL || ""),
    title: title || siteName,
    description: description || siteDescription,
    openGraph: openGraph || {
      type: "website",
      url: process.env.NEXT_PUBLIC_BASE_URL,
      title: "Create Next App",
      description: "Generated by create next app",
      images: [
        {
          url: "/preview.jpg",
          alt: "Preview image",
          width: 1200,
          height: 630,
        },
      ],
    },
    twitter: twitter || {
      handle: "@vercel",
      site: "@vercel",
      cardType: "summary_large_image",
    },
    icons: icons || [
      {
        url: favicon?.image_url,
        rel: "icon",
        type: "image/x-icon",
      },
    ],
  };
};
