### check status v1
GET http://localhost:9000/v1/checkstatus

### check status v1/admin
GET http://localhost:9000/v1/admin/checkstatus


### login
POST http://localhost:9000/v1/admin/login
Content-Type: "application/json"

{
  "username": "admin",
  "password": "1"
}

### logout
POST http://localhost:9000/v1/admin/logout HTTP/1.1
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIwOTE2MDc0NiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.AVGzMul0i8hTLyaeOhVX1mtpNiVbEKWqd3bwvoaMPTg"
Content-Type: "application/json"

### get All Users
GET http://localhost:9000/v1/admin/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIwOTE2MDc0NiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.AVGzMul0i8hTLyaeOhVX1mtpNiVbEKWqd3bwvoaMPTg
Content-Type: "application/json"

### get user by id
GET http://localhost:9000/v1/admin/users/2
Authorization: 1
Content-Type: "application/json"

### update user
PUT http://localhost:9000/v1/admin/users/2
Authorization: 1
Content-Type: "application/json"

{
  "username": "admin2",
  "password": "123123",
  "user_email": "admin@gmail.com",
  "user_active": 1
}

### delete user
DELETE http://localhost:9000/v1/admin/users/2
Authorization: 1

### create new user
POST http://localhost:9000/v1/admin/users
Authorization: 1
Content-Type: "application/json"

{
  "username": "admin",
  "password": "123123",
  "user_email": "admin@gmail.com"
}

---------------------------------------

### get all config
GET http://localhost:9000/v1/config
Authorization: 1

### get config by key
GET http://localhost:9000/v1/config/key/site_name

### get config by id
GET http://localhost:9000/v1/admin/configs/3
Authorization: 1

### create new config
POST http://localhost:9000/v1/admin/configs
Authorization: 1
Content-Type: "application/json"

{
  "config_key": "admin_email",
  "config_value": "meo@meo.com",
  "config_style":""
}

### update config
PUT http://localhost:9000/v1/admin/configs/4
Authorization: 1
Content-Type: "application/json"

{
  "config_key": "logo_url",
  "config_value": "https://umex-bucket-s3.s3.ap-southeast-1.amazonaws.com/umex/1735786792050_next.svg",
  "config_style": ""
}

### delete config
DELETE http://localhost:9000/v1/admin/configs/5
Authorization: 1

------------------------------------

### get all component
GET http://localhost:9000/v1/component

### create new component
POST http://localhost:9000/v1/admin/components
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxNDIyMDcyMSwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19._3CXKpFpOXS4pzrUmgVBiqceGYCX5CZ8KAN41DNZgMg
Content-Type: "application/json"

{
  "comp_name": "Mobile-Logo",
  "comp_position": 0,
  "comp_map": "Logo"
}

### get component name
GET http://localhost:9000/v1/component/name/menu

### get component position
GET http://localhost:9000/v1/component/position/0

### get component by id
GET http://localhost:9000/v1/admin/components/1
Authorization: 1

### update component
PUT http://localhost:9000/v1/admin/components/26
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxNDIyMDcyMSwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19._3CXKpFpOXS4pzrUmgVBiqceGYCX5CZ8KAN41DNZgMg
Content-Type: application/json

{
  "comp_name": "Mobile-Logo",
  "comp_position": 11,
  "comp_index": 1
}

### delete component
DELETE http://localhost:9000/v1/admin/components/2
Authorization: 1

---------------------------------------

### get all image
GET http://localhost:9000/v1/admin/images
Authorization: 1

### create a new image
POST http://localhost:9000/v1/admin/images
Authorization: 1
Content-Type: "application/json"

{
  "img_src": "https://umex-bucket-s3.s3.ap-southeast-1.amazonaws.com/umex/1735786792050_next.svg",
  "img_alt": "Logo UMEX",
  "img_title": "Logo",
  "img_caption": "logo caption"
}

### get image by id
GET http://localhost:9000/v1/admin/images/1
Authorization: 1

### update image
PUT http://localhost:9000/v1/admin/images/1
Authorization: 1

{
  "img_src": "https://umex-bucket-s3.s3.ap-southeast-1.amazonaws.com/umex/1735786792050_next.svg",
  "img_title": "update title",
  "img_alt": "update alt",
  "img_caption": "update caption"
}

### delete image
DELETE http://localhost:9000/v1/admin/images/2
Authorization: 1

---------------------------------------

### get all menu
GET http://localhost:9000/v1/admin/menus
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIwOTE2MDc0NiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.AVGzMul0i8hTLyaeOhVX1mtpNiVbEKWqd3bwvoaMPTg

### create new menu
POST http://localhost:9000/v1/admin/menus
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIwOTE2MDc0NiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.AVGzMul0i8hTLyaeOhVX1mtpNiVbEKWqd3bwvoaMPTg
Content-Type: "application/json"

{
  "menu_name": "Menu 2",
  "menu_value": "{\"giday\": \"khong biet\"}"
}

### update menu
PUT http://localhost:9000/v1/admin/menus/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIwOTE2MDc0NiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.AVGzMul0i8hTLyaeOhVX1mtpNiVbEKWqd3bwvoaMPTg
Content-Type: "application/json"

{
  "menu_name": "Menu main",
  "menu_value": "{\"giday\": \"biet roi\"}"
}

### delete menu
DELETE http://localhost:9000/v1/admin/menus/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIwOTE2MDc0NiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.AVGzMul0i8hTLyaeOhVX1mtpNiVbEKWqd3bwvoaMPTg

### get menu by Id
GET http://localhost:9000/v1/menu/1

------------------------------------------------------

### get all menu location
GET http://localhost:9000/v1/admin/menu_locations
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIwOTE2MDc0NiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.AVGzMul0i8hTLyaeOhVX1mtpNiVbEKWqd3bwvoaMPTg

### get menu location by id
GET http://localhost:9000/v1/admin/menu_locations/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIwOTE2MDc0NiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.AVGzMul0i8hTLyaeOhVX1mtpNiVbEKWqd3bwvoaMPTg

### update menu location
PUT http://localhost:9000/v1/admin/menu_locations/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIwOTE2MDc0NiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.AVGzMul0i8hTLyaeOhVX1mtpNiVbEKWqd3bwvoaMPTg
Content-Type: "application/json"

{
  "menu_id": 0
}

### get location by menu id
GET http://localhost:9000/v1/admin/menu_locations/menu/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIwOTE2MDc0NiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.AVGzMul0i8hTLyaeOhVX1mtpNiVbEKWqd3bwvoaMPTg

---------------------------------------------------------------

### get all type
GET http://localhost:9000/v1/admin/types
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

### get type by id
GET http://localhost:9000/v1/admin/types/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

### create new type
POST http://localhost:9000/v1/admin/types
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

{
  "type_name": "Sample Type 2"
}

### update type
PUT http://localhost:9000/v1/admin/types/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

{
  "type_name": "Updated Type"
}

### delete type
DELETE http://localhost:9000/v1/admin/types/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

---------------------------------------------------

### get all category
GET http://localhost:9000/v1/admin/categories
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIyMTA4MzgyMSwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiJhZG1pbiIsInVzZXJfZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSJ9fQ.4L-HOXt0hoMEgVLkL-5D9IbdYD3FGk8EsdsM6Ma9UJw
Content-Type: "application/json"

### create new category
POST http://localhost:9000/v1/admin/categories
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

{
	"category_name": "Cat Name 2",
	"category_slug": "cat_name_2",
	"category_des": " hahah cat description here",
	"type_id": 1
}

### get category by id
GET http://localhost:9000/v1/admin/categories/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

### update category
PUT http://localhost:9000/v1/admin/categories/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

{
  "category_name": "Updated Cat Name",
  "category_slug": "updated_cat_name",
  "category_des": " updated cat description here",
  "type_id": 1
}

### delete category
DELETE http://localhost:9000/v1/admin/categories/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

-------------------------------------------

### get all page
GET http://localhost:9000/v1/admin/pages?limit=10&offset=0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIyMTA4MzgyMSwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiJhZG1pbiIsInVzZXJfZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSJ9fQ.4L-HOXt0hoMEgVLkL-5D9IbdYD3FGk8EsdsM6Ma9UJw
Content-Type: "application/json"

### create new page
POST http://localhost:9000/v1/admin/pages
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIyMTA4MzgyMSwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiJhZG1pbiIsInVzZXJfZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSJ9fQ.4L-HOXt0hoMEgVLkL-5D9IbdYD3FGk8EsdsM6Ma9UJw
Content-Type: "application/json"

{
  "page_title": "page 22",
  "page_content": "This is a sample page content",
  "page_description": "this is a description",
	"page_slug": "page_22",
	"page_year": 2025,
	"page_month": 2,
	"page_day": 19,
	"user_id": 1,
	"type_id": 1
}

### get page by id
GET http://localhost:9000/v1/admin/pages/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

### get page by slug
GET http://localhost:9000/v1/admin/pages/slug/page_2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

### get page by year
GET http://localhost:9000/v1/admin/pages/year?year=2025&limit=10&offset=0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

### get page by month
GET http://localhost:9000/v1/admin/pages/month?month=2&year=2025&limit=10&offset=0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

### get page by day
GET http://localhost:9000/v1/admin/pages/day?day=18&month=2&year=2025&limit=10&offset=0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

### get page by type
GET http://localhost:9000/v1/admin/pages/type/1?limit=10&offset=0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

### get page by status
GET http://localhost:9000/v1/admin/pages/status/0?limit=10&offset=0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

### get page by trash
GET http://localhost:9000/v1/admin/pages/trash/1?limit=10&offset=0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

### get page by type and status
GET http://localhost:9000/v1/admin/pages/typestatus?type=1&status=0&limit=10&offset=0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIyMTA4MzgyMSwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiJhZG1pbiIsInVzZXJfZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSJ9fQ.4L-HOXt0hoMEgVLkL-5D9IbdYD3FGk8EsdsM6Ma9UJw
Content-Type: "application/json"

### update page
PUT http://localhost:9000/v1/admin/pages/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

{
  "page_title": "page updated",
  "page_content": "This is a sample page content",
  "page_description": "this is a description",
	"page_slug": "page_updated",
	"page_year": 2025,
	"page_month": 1,
	"page_day": 10,
	"user_id": 1,
	"type_id": 1,
  "category_id": 1,
  "page_trash": 1
}

### delete page
DELETE http://localhost:9000/v1/admin/pages/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

---------------------------------------------

### get all tag
GET http://localhost:9000/v1/admin/tags
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIyMTA4MzgyMSwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiJhZG1pbiIsInVzZXJfZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSJ9fQ.4L-HOXt0hoMEgVLkL-5D9IbdYD3FGk8EsdsM6Ma9UJw
Content-Type: "application/json"

### create new tag
POST http://localhost:9000/v1/admin/tags
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIyMTA4MzgyMSwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiJhZG1pbiIsInVzZXJfZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSJ9fQ.4L-HOXt0hoMEgVLkL-5D9IbdYD3FGk8EsdsM6Ma9UJw
Content-Type: "application/json"

{
  "tag_name": "tag 1",
	"tag_slug": "tag_1",
	"tag_description": "day la tag 1",
	"type_id": 1
}

### get tag by id
GET http://localhost:9000/v1/admin/tags/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

### get tag by slug
GET http://localhost:9000/v1/admin/tags/slug/tag_2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

### get tag by type
GET http://localhost:9000/v1/admin/tags/type/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

### update tag
PUT http://localhost:9000/v1/admin/tags/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

{
  "tag_name": "tag 1111101",
	"tag_slug": "tag_1",
	"tag_description": "day la tag 1",
	"type_id": 1
}

### delete tag
DELETE http://localhost:9000/v1/admin/tags/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIxOTA5NTg0MiwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiIxIiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19.qEkHYvQKeicPGwe0EtvxX83hqnNW-KDVFtFtDqBofUA
Content-Type: "application/json"

----------------------------------------------

### create new page tag
POST http://localhost:9000/v1/admin/pagetags
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIyMTA4MzgyMSwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiJhZG1pbiIsInVzZXJfZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSJ9fQ.4L-HOXt0hoMEgVLkL-5D9IbdYD3FGk8EsdsM6Ma9UJw
Content-Type: "application/json"

{
  "page_id": 1,
	"tag_id":1
}

### get page by tag
GET http://localhost:9000/v1/admin/pagetags/tag/1?limit=10&offset=0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIyMTA4MzgyMSwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiJhZG1pbiIsInVzZXJfZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSJ9fQ.4L-HOXt0hoMEgVLkL-5D9IbdYD3FGk8EsdsM6Ma9UJw
Content-Type: "application/json"

### get tag by page
GET http://localhost:9000/v1/admin/pagetags/page/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIyMTA4MzgyMSwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiJhZG1pbiIsInVzZXJfZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSJ9fQ.4L-HOXt0hoMEgVLkL-5D9IbdYD3FGk8EsdsM6Ma9UJw
Content-Type: "application/json"
-------------------------------------------------

### create new page category
POST http://localhost:9000/v1/admin/pagecategories
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIyMTA4MzgyMSwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiJhZG1pbiIsInVzZXJfZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSJ9fQ.4L-HOXt0hoMEgVLkL-5D9IbdYD3FGk8EsdsM6Ma9UJw
Content-Type: "application/json"

{
  "page_id": 1,
  "category_id":1
}

### get page by category
GET http://localhost:9000/v1/admin/pagecategories/category/1?limit=10&offset=0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIyMTA4MzgyMSwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiJhZG1pbiIsInVzZXJfZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSJ9fQ.4L-HOXt0hoMEgVLkL-5D9IbdYD3FGk8EsdsM6Ma9UJw
Content-Type: "application/json"

### get category by page
GET http://localhost:9000/v1/admin/pagecategories/page/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzX2F0IjoyMDI1MDIyMTA4MzgyMSwicGF5bG9hZCI6eyJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiJhZG1pbiIsInVzZXJfZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSJ9fQ.4L-HOXt0hoMEgVLkL-5D9IbdYD3FGk8EsdsM6Ma9UJw
Content-Type: "application/json"