import {
  Fa500Px,
  FaDiscord,
  FaEnvelope,
  FaFacebookF,
  FaFlickr,
  FaInstagram,
  FaLinkedinIn,
  FaPhone,
  FaPinterestP,
  FaRss,
  FaTelegram,
  FaTiktok,
  FaTwitch,
  FaXTwitter,
  FaYoutube,
} from "react-icons/fa6";
import { IconType } from "react-icons/lib";

export const IconsMap: Record<number, string> = {
  1: "Facebook",
  2: "Instagram",
  3: "TikTok",
  4: "X",
  5: "E-mail",
  6: "Phone",
  7: "Pinterest",
  8: "RSS",
  9: "LinkedIn",
  10: "YouTube",
  11: "Flickr",
  12: "500px",
  13: "Telegram",
  14: "Twitch",
  15: "Discord",
};

export const IconsIcoMap: Record<number, IconType> = {
  1: FaFacebookF,
  2: FaInstagram,
  3: FaTiktok,
  4: FaXTwitter,
  5: FaEnvelope,
  6: FaPhone,
  7: FaPinterestP,
  8: FaRss,
  9: FaLinkedinIn,
  10: FaYoutube,
  11: FaFlickr,
  12: Fa500Px,
  13: FaTelegram,
  14: FaTwitch,
  15: FaDiscord,
};
