import { BsChat } from "react-icons/bs";
import {
  FaArrowDown,
  FaArrowLeft,
  FaArrowRight,
  FaArrowUp,
  FaCertificate,
  FaCheck,
  FaDiscord,
  FaDribbble,
  FaExpandAlt,
  FaFacebookF,
  FaGift,
  FaHeart,
  FaInstagram,
  FaLinkedin,
  FaMapMarkedAlt,
  FaPen,
  FaPinterest,
  FaRegClock,
  FaRegHeart,
  FaRegUser,
  FaRss,
  FaSearch,
  FaShoppingBag,
  FaShoppingBasket,
  FaShoppingCart,
  FaSnapchatGhost,
  FaStar,
  FaTag,
  FaTelegram,
  FaTiktok,
  FaTwitter,
  FaUser,
  FaYoutube,
} from "react-icons/fa";
import { FaPhone, FaThreads, FaX } from "react-icons/fa6";
import { LuMenu } from "react-icons/lu";
import { TiLockClosed, TiLockOpen, TiMail } from "react-icons/ti";

export const iconMap = {
  Facebook: FaFacebookF,
  Instagram: FaInstagram,
  TikTok: FaTiktok,
  Twitter: FaTwitter,
  Threads: FaThreads,
  Mail: TiMail,
  Phone: FaPhone,
  Pinterest: FaPinterest,
  Rss: FaRss,
  LinkedIn: FaLinkedin,
  YouTube: FaYoutube,
  Telegram: FaTelegram,
  Discord: FaDiscord,
  SnapChat: FaSnapchatGhost,
  ArrowLeft: FaArrowLeft,
  ArrowRight: FaArrowRight,
  ArrowUp: FaArrowUp,
  ArrowDown: FaArrowDown,
  Certificate: FaCertificate,
  Chat: BsChat,
  CheckMark: FaCheck,
  Clock: FaRegClock,
  Cross: FaX,
  Dribbble: FaDribbble,
  Expand: FaExpandAlt,
  Gift: FaGift,
  Heart: FaHeart,
  HeartOutline: FaRegHeart,
  Lock: TiLockClosed,
  UnLock: TiLockOpen,
  MapPin: FaMapMarkedAlt,
  Menu: LuMenu,
  Pen: FaPen,
  Search: FaSearch,
  ShoppingBag: FaShoppingBag,
  ShoppingBasket: FaShoppingBasket,
  ShoppingCart: FaShoppingCart,
  Star: FaStar,
  Tag: FaTag,
  User: FaUser,
  UserOutline: FaRegUser,
};
